### ISSUE TITLE
Problem when a user connects without being registered.

### ISSUE THREAD

**Issue by Maolam10** [lenis0012/LoginSecurity#318]
I get this error when a user enters the server without being registered (/register), but it doesn't happen when they are (/login). If I delete the password for a user who had already registered and they connect, the error appears again. Also, they don't appear at the spawn point but about ten blocks away. The spawn issue doesn't occur when you connect and are registered.

[17:29:33 WARN]: [LoginSecurity] Failed to set inventory id in profile
[17:29:33 ERROR]: [LoginSecurity] Failed to save player location
java.sql.SQLException: Failed set location id in profile
	at com.lenis0012.bukkit.loginsecurity.database.LocationRepository.insertLoginLocationBlocking(LocationRepository.java:61) ~[LoginSecurity-3.2.1-Spigot.jar:?]
	at com.lenis0012.bukkit.loginsecurity.database.LocationRepository.lambda$insertLoginLocation$0(LocationRepository.java:30) ~[LoginSecurity-3.2.1-Spigot.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-95]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-95]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by lenis0012** [comment]
Did you try the latest dev build?
