### ISSUE TITLE
The player did not prompt to log in when entering the game

### ISSUE THREAD

**Issue by aiyaodada** [lenis0012/LoginSecurity#330]
你好我是一名中国的Minecraft服主，我今天发现，不用登录就可以进入游戏了，我最开始以为版本问题，我换到3.3.0然后重载了下插件还是不需要登录，我未链接数据库，应该不是数据库问题，我进入游戏时未提示登录，我输入/login 密码 提示An internal error occurred while attempting to perform this command

**Comment by aiyaodada** [comment]
Now enter the/lac command and report An internal error occurred while attaching to perform this command
In the log, there are
[10:04:10] [Server thread/INFO]: [LoginSecurity] Enabling LoginSecurity v3.3.0
[10:04:10] [Server thread/INFO]: [LoginSecurity] Loading base translations from "en_us"
[10:04:10] [Server thread/INFO]: [LoginSecurity] Loading specified translations from "en_us"
[10:04:10] [Server thread/INFO]: [LoginSecurity] Registering commands...
[10:04:10] [Server thread/INFO]: [LoginSecurity] Registering listeners...
[10:04:10] [Server thread/ERROR]: Error occurred while enabling LoginSecurity v3.3.0 (Is it up to date?)
java.lang.IllegalStateException: No updater implementation found
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.updater.UpdaterFactory.lambda$provideBest$2(UpdaterFactory.java:29) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_312]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.updater.UpdaterFactory.provideBest(UpdaterFactory.java:29) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.modules.general.GeneralModule.setupUpdater(GeneralModule.java:61) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.modules.general.GeneralModule.enable(GeneralModule.java:32) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.modules.ModuleRegistry.enableModule(ModuleRegistry.java:82) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_312]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_312]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_312]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_312]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_312]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.modules.ModuleRegistry.enableModules(ModuleRegistry.java:59) ~[?:?]
	at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.modules.ModularPlugin.onEnable(ModularPlugin.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[1.12.jar:git-Paper-1604]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[1.12.jar:git-Paper-1604]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[1.12.jar:git-Paper-1604]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[1.12.jar:git-Paper-1604]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[1.12.jar:git-Paper-1604]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[1.12.jar:git-Paper-1604]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[1.12.jar:git-Paper-1604]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[1.12.jar:git-Paper-1604]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[1.12.jar:git-Paper-1604]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[1.12.jar:git-Paper-1604]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[10:04:10] [Server thread/INFO]: [LoginSecurity] Disabling LoginSecurity v3.3.0
[10:04:10] [Server thread/INFO]: [LoginSecurity] Waiting for queued tasks...
[10:04:10] [Server thread/INFO]: [LoginSecurity] ExecutorService shut down, ready to disable.

**Comment by jfoucher** [comment]
I get the same `No updater implementation found`  after compiling from source
